Creating new use case for get orders api
dvdonadelli/food-challenge pull request #15
Opened 2024-01-25 20:02 UTC by palmeiira

2024-01-27 17:17 UTC, dvdonadelli requested changes
@palmeiira deixei aqui todas as sugestões meu amigo!

2024-01-27 17:17 UTC, dvdonadelli commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/domain/entities/order/Order.kt
> +    val createdAt: LocalDateTime
aqui eu acho melhor ficar como default da propriedade `createdAt` o valor de agora, deixando a declaração assim: `val createdAt: LocalDateTime = LocalDateTime.now()`

assim toda vez que um objeto de domínio for instanciado, mesmo que seja pelo nosso método estático de fábrica, não precisamos nos preocupar se estamos passando a data certa ou não

2024-01-27 17:17 UTC, dvdonadelli commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/domain/entities/order/Order.kt
> +            return Order(customerCpf = customerId, items = items, status = OrderStatus.RECEIVED, createdAt = LocalDateTime.now())
aí tiramos o createdAt desta instanciação

2024-01-27 17:17 UTC, dvdonadelli commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/domain/entities/order/Order.kt
> +            return Order(entity.id, entity.customerCpf?.let { CPF(it) }, items, entity.status, LocalDateTime.now())
aí o único lugar que atualiza de fato a data de um pedido, é a criação de um pedido, faz sentido ?

quando estivermos mapeando da nossa base de dados para a aplicação, não queremos atualizar essa data, então o final desse método ficaria: 

```kotlin
fun fromEntity(entity: OrderEntity, objectMapper: ObjectMapper): Order {
    val items: List<OrderItem> = objectMapper.treeToValue(entity.itemsData)
    return Order(
        entity.id,
        entity.customerCpf?.let { CPF(it) },
        items,
        OrderStatus.valueOf(entity.status),
        entity.createdAt
    )
}
```

2024-01-27 17:17 UTC, dvdonadelli commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/domain/entities/order/comparator/OrderComparator.kt
aí vai poder deletar essa classe inteira também kkkk

2024-01-27 17:17 UTC, dvdonadelli commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/infrastructure/persistence/entities/OrderEntity.kt
> +    val createdAt: LocalDateTime
esse atributo na nossa entidade não precisa ser serializado, o Spring Data toma conta pra a gente de guardar ele na base com o tipo correto, aí eu renomearia a coluna pra seguir o padrão camel_case das outras: 

```kotlin
@Column(name = "created_at")
val createdAt: LocalDateTime
```

2024-01-27 17:17 UTC, dvdonadelli commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/infrastructure/persistence/entities/OrderEntity.kt
> +                LocalDateTime.now()
aqui mesmo comentário do método `fromEntity` na nossa classe de domínio, o único lugar que realmente cria e passa um valor para o nosso `createdAt` é o próprio domínio, aqui ficaria só o mapeamento mesmo: 

```kotlin
fun fromDomain(domainObject: Order, objectMapper: ObjectMapper): OrderEntity {
    val itemsData = objectMapper.valueToTree<JsonNode>(domainObject.items)
    return OrderEntity(
        id = domainObject.id,
        customerCpf = domainObject.customerCpf?.value,
        itemsData = itemsData,
        status = domainObject.status.name,
        createdAt = domainObject.createdAt
    )
}
```

2024-01-27 17:17 UTC, dvdonadelli commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/application/gateways/OrderGateway.kt
> +    fun findInStatus(status: List<OrderStatus>): List<Order>
aqui eu renomearia esse método para algo mais idiomático, e foi o nome que eu deixei no comentário da nossa classe de use-case

```kotlin
fun findActiveOrdersSorted(): List<Order>
```

2024-01-27 17:17 UTC, dvdonadelli commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/infrastructure/persistence/entities/OrderEntity.kt
> +    val status: OrderStatus,
e essa propriedade aqui vamos alterar para uma simples String, já que não queremos expor alguma classe do nosso domínio para nada externo, e podemos remover também essa anotação @Enumerated(EnumType.STRING)

isso vai facilitar o Repository

```kotlin
val status: String,
```

2024-01-27 17:17 UTC, dvdonadelli commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/infrastructure/persistence/OrderRepository.kt
> +    fun findByStatus(status: OrderStatus): List<OrderEntity>
aí agora este método precisa receber como parâmetro só a String representando o status: 

```kotlin
fun findByStatus(status: String): List<OrderEntity>
```

2024-01-27 17:17 UTC, dvdonadelli commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/infrastructure/persistence/OrderRepository.kt
> +    fun findByStatusIn(status: List<OrderStatus>) : List<OrderEntity>
e este método aqui vai executar uma query bonintona pra a gente resolver mais rápido esse filtro e ordenação

```kotlin
@Query("SELECT o FROM OrderEntity o WHERE o.status NOT IN ('COMPLETED', 'CANCELED') ORDER BY CASE o.status WHEN 'READY' THEN 1 WHEN 'IN_PREPARATION' THEN 2 WHEN 'RECEIVED' THEN 3 ELSE 4 END, o.createdAt")
fun findActiveOrdersSorted(): List<OrderEntity>
```

2024-01-27 17:17 UTC, dvdonadelli commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/infrastructure/gateways/OrderRepositoryGateway.kt
> +    override fun findByStatus(status: OrderStatus) =
agora esse método também precisa alterar pra enviar o status.name ao invés do status pro nosso repository: 

```kotlin
override fun findByStatus(status: OrderStatus) =
    orderRepository.findByStatus(status.name).map { Order.fromEntity(it, objectMapper) }
```

2024-01-27 17:17 UTC, dvdonadelli commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/infrastructure/gateways/OrderRepositoryGateway.kt
> +    override fun findInStatus(status: List<OrderStatus>) =
e este aqui vira a nova implementação do `findActiveOrdersSorted()` no nosso gateway

```kotlin
override fun findActiveOrdersSorted() =
    orderRepository.findActiveOrdersSorted().map { Order.fromEntity(it, objectMapper) }
```

2024-01-27 17:17 UTC, dvdonadelli commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/infrastructure/persistence/entities/OrderEntity.kt
>  @Table(name = "orders")
e aqui também vamos incluir os índices na nossa tabela pra melhorar ainda mais a performance e escalabilidade da nossa query né:

```kotlin
@Entity
@Table(
    name = "orders", indexes = [
        Index(name = "idx_status", columnList = "status"),
        Index(name = "idx_created_at", columnList = "created_at")
    ]
)
data class OrderEntity(...
```

2024-01-27 17:17 UTC, dvdonadelli commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/infrastructure/controller/order/OrderResponse.kt
aí eu adicionaria o nosso campo createdAt aqui também, só pra expor e pra validar certinho que estamos respondendo ordenado corretamente os nossos pedidos: 

```kotlin
data class OrderResponse(
    val orderId: Long,
    val status: String,
    val createdAt: LocalDateTime
) {
    companion object {
        fun fromDomain(domainObject: Order) =
            domainObject.id?.let { OrderResponse(it, domainObject.status.name, domainObject.createdAt) }
    }
}
```

2024-01-28 17:33 UTC, palmeiira commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/configuration/JacksonConfig.kt
> +                    .addSerializer(LocalDateTime::class.java, LocalDateTimeSerializer())
Obrigado, Davi. Não conhecia esse módulo do Jackson!

2024-01-28 17:34 UTC, palmeiira commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/domain/entities/order/Order.kt
> +            return Order(entity.id, entity.customerCpf?.let { CPF(it) }, items, entity.status, LocalDateTime.now())
@dvdonadelli Tinha um bug que eu deixei passar aqui. Obrigado pela observação.

2024-01-28 17:35 UTC, palmeiira commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/infrastructure/persistence/entities/OrderEntity.kt
> +                LocalDateTime.now()
@dvdonadelli outro bug que deixei passar por falta de atenção .Obrigado pela correção!!

2024-01-28 17:35 UTC, palmeiira commented on src/main/kotlin/br/com/fiap/postech/foodchallenge/infrastructure/persistence/entities/OrderEntity.kt
> +    val status: OrderStatus,
@dvdonadelli achei muito legal esse análise de não expor o domínio pro externo. Bacana observação.

2024-01-28 21:41 UTC, dvdonadelli approved these changes
LGTM

2024-01-28 21:41 UTC, merged